export const articles = [
  {
    id: 1,
    title: "Breakthrough in Carbon Capture Technology Promises Cheaper Emission Reductions",
    source: "Reuters",
    date: "2025-09-19T10:00:00Z",
    category: "Tech",
    bookmarked: true,
  },
  {
    id: 2,
    title: "Global Leaders Agree on New Climate Accord at Geneva Summit",
    source: "The Guardian",
    date: "2025-09-19T08:30:00Z",
    category: "Policy",
    bookmarked: false,
  },
  {
    id: 3,
    title: "Next-Generation Solar Panels Reach Record 40% Efficiency in Lab Tests",
    source: "CleanTechnica",
    date: "2025-09-18T15:00:00Z",
    category: "Energy",
    bookmarked: false,
  },
  {
    id: 4,
    title: "The Role of AI in Predicting and Mitigating Wildfire Risks",
    source: "Tech Today",
    date: "2025-09-18T11:45:00Z",
    category: "Tech",
    bookmarked: true,
  },
  {
    id: 5,
    title: "New EU Regulations Target Corporate Greenwashing",
    source: "Global News",
    date: "2025-09-17T18:00:00Z",
    category: "Policy",
    bookmarked: false,
  },
];